In [2]:
import numpy as np
import pandas as pd

In [13]:
data = pd.read_csv("./data.csv", names=["x1", "x2", "target"])

In [14]:
data

x1        x2  target
0   0.78051 -0.063669       1
1   0.28774  0.291390       1
2   0.40714  0.178780       1
3   0.29230  0.421700       1
4   0.50922  0.352560       1
..      ...       ...     ...
95  0.77029  0.701400       0
96  0.73156  0.717820       0
97  0.44556  0.579910       0
98  0.85275  0.859870       0
99  0.51912  0.623590       0

[100 rows x 3 columns]

In [22]:
input_np = data[["x1", "x2"]].to_numpy()

In [23]:
target_np = data[["target"]].to_numpy()

In [29]:
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    
    for i in range(len(X)):
        y_hat_i = prediction(X[i], W, b)
        
        if y_hat_i == 0 and y[i] == 1:
            W[0] = W[0] + learn_rate*X[i][0]
            W[1] = W[1] + learn_rate*X[i][1]
            
        elif y_hat_i == 1 and y[i] == 0:
            W[0] = W[0] - learn_rate*X[i][0]
            W[1] = W[1] - learn_rate*X[i][1]
        
    return W, b
    
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [28]:
trainPerceptronAlgorithm(input_np, target_np)

[(array([-0.05239463]), array([-2.8808521])),
 (array([1.23772563]), array([-6.88108786])),
 (array([-6.69291623]), array([17.70920662])),
 (array([-2.23027859]), array([3.87204494])),
 (array([-1.69006436]), array([2.19736513])),
 (array([-1.54903116]), array([1.76151734])),
 (array([-1.49916697]), array([1.60034642])),
 (array([-1.47231239]), array([1.50887035])),
 (array([-1.45280355]), array([1.45323219])),
 (array([-1.43476789]), array([1.40705089])),
 (array([-1.42196412]), array([1.38168698])),
 (array([-1.40961379]), array([1.35722131])),
 (array([-1.39904984]), array([1.3439204])),
 (array([-1.38869094]), array([1.33087767])),
 (array([-1.37853116]), array([1.31808566])),
 (array([-1.36856484]), array([1.30553722])),
 (array([-1.35878649]), array([1.29322545])),
 (array([-1.34919084]), array([1.28114372])),
 (array([-1.33977282]), array([1.26928564])),
 (array([-1.33052755]), array([1.25764507])),
 (array([-1.32145032]), array([1.24621606])),
 (array([-1.31253658]), array([1.2